# Generated by Django 6.0.2 on 2026-02-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='togri',
            options={'verbose_name': "Tog'ri so'z", 'verbose_name_plural': "Tog'ri so'zlar"},
        ),
        migrations.AlterField(
            model_name='togri',
            name='soz',
            field=models.CharField(max_length=100, verbose_name="so'z"),
        ),
        migrations.CreateModel(
            name='Notogri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soz', models.CharField(max_length=100, verbose_name="so'z")),
                ('togri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.togri')),
            ],
            options={
                'verbose_name': "Notog'ri so'z",
                'verbose_name_plural': "Notog'ri so'zlar",
            },
        ),
        migrations.DeleteModel(
            name='Notogrig',
        ),
    ]
